body:

- type: markdown
  attributes:
    value: |
      Write a descriptive title for your proposal above and provide as much detail as you can in the fields below. If your idea is not fully fleshed out yet, please open a discussion in [General](https://github.com/orgs/ivoyager/discussions/categories/general) instead. _(This is a new experimental template! Please give feedback in General discussion if you think it needs imporovement!)_

- type: textarea
  attributes:
    label: Describe what is missing or deficient and why it should be part of or improved in I, Voyager
    placeholder: Example - "The Planetarium doesn't have comets. Comets are important solar system bodies that should be included."
  validations:
    required: true

- type: textarea
  attributes:
    label: If this is a simulator "content" proposal, please describe how the content should appear and how users should interact with the content.
    placeholder: Example - "Comets orbits and point locations should be visible in the same way that asteroids are currently. They should have thier own category in the GUI panel under the asteroid groups."
  validations:
    required: false

- type: textarea
  attributes:
    label: If this is a code or "game/app development platform" proposal, please describe as much API detail as possible. How are developers going to interface with this new feature?
    placeholder: N/A for our comet example
  validations:
    required: false

- type: textarea
  attributes:
    label: If applicable, please provide implementation code, pseudo-code, mock-ups, diagrams, or orbital maths. Do you have any helpful tips or gotchas to watch out for?
    placeholder: Example - "Watch out! Some comets are listed with eccentricity > 1.0. These have hyperbolic trajectory through the inner solar system, but become elliptical as they move into the Oort cloud."
  validations:
    required: false

- type: textarea
  attributes:
    label: Which of the following describes your feature? (1) A feature or content improvement for our Planetarium. (2) An improvement to help game/app developers that should be core. (3) An improvement to help game/app developers that should be an optional addon.
    placeholder: Example - "Definitely (1) and possibly (2) (a game developer might want comets).
  validations:
    required: true
